### ISSUE TITLE
Erro ao acessar algumas rotas vinculadas ao mural

### ISSUE THREAD

**Issue by stefanimeneghetti** [practice-uffs/api#19]
Ao tentar acessar rotas do tipo `v0/mural/orders/{id}` recebemos um "Not found" como resposta.

![image](https://user-images.githubusercontent.com/51202548/142490815-c2d6a677-98ea-4492-931c-48909868b2ce.png)

Imagino que isso ocorra porque no arquivo de rotas apenas a rota get para `v0/mural/orders` é especificada. 

![image](https://user-images.githubusercontent.com/51202548/142492609-53020f53-1f12-4fd8-9f18-8b979660ce6d.png)

Provavelmente é apenas esse problema que esta causando o erro relatado [nessa issue do aplicativo](https://github.com/practice-uffs/app-practice/issues/186) já que não é possível acessar a rota necessária. As outras rotas do mural (categorias, serviços...) também possuem o mesmo problema.

**Comment by Dovyski** [comment]
O problema foi corrigido em 28d0a0eecf83d6b560badcfdf58b6b0b49e47e33 (na branch `dev`).
