### ISSUE TITLE
Criar a documentação da API

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/api#2]
A criar a documentação da API com as rotas já disponíveis

**Comment by CleissonVieira** [comment]
@Dovyski daria para nós inserir a documentação da API [nesta pasta](https://drive.google.com/drive/u/0/folders/1AxDA7xDbmomoA_i_SIUn_UYksbfZYuvf) do drive

**Comment by Dovyski** [comment]
A documentação da API é gerada de forma automática agora, basta rodar `php artisan l5-swagger:generate` no repositório da API (a documentação ficará disponível em `localhost/documentation`). Existem, porém, vários métodos que não foram documentados ainda.

Acho que seria interessante fazer isso e deixar a documentação centralizada no próprio projeto.
