### ISSUE TITLE
Widget web de interação da Aura

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/api#21]
O objetivo dessa issue é replicar o chat de interação da Aura existente no app-practice em uma outra página web (servida junto com a api). A url/rota da api que servirá essa página será `GET /v0/widgets/aura`.

Existem dois caminhos possíveis para se seguir (faz parte dessa tarefa analisar eles e fazer a decisão)

- Tentar utilizar ao máximo o código/estilo/estrutura do app-practice (e por tabela o framework7). Nesse caso, teríamos que remover tudo que é relacionado com o app e deixar só a tela da aura (remover header, storage, etc). A vantagem é que implementações futuras da Aura no app podem ser "facilmente" adaptadas para o widget, mantendo os depois com paridade de funcionalidades. A desvantagem maior é que contorcer o framework7 para isso talvez seja muito mais complicado do que implementar somente a tela do chat da Aura do zero utilizando html/css/js puro.

- Implementar essa página do zero, utilizando html/css/js. A vantagem é que temos controle total do que será feito, inclusive replicar o layout do chat (que não é difícil de ser feito). A desvantagem é que, se implementarmos algo novo no app practice da Aura, teremos que portar isso para o widget.

Faz parte dessa tarefa também fazer o JS responsável por enviar as perguntas do chat para a API da Aura receber como parâmetro GET da URL da página o token do usuário. Por exemplo, imaginando que a página do widget é `https://practice.uffs.edu.br/api/v0/widgets/aura` e que ele seja colocado em um iframe em alguma página qualquer (do mural), ela seria colocada assim:

```html
<iframe src="https://practice.uffs.edu.br/api/v0/widgets/aura?token=TOKEN_DO_USUARIO_AQUI"></iframe>
```
A página servida de `https://practice.uffs.edu.br/api/v0/widgets/aura` carregará o chat e o seu JS normalmente. O JS deverá buscar a query parameter `token` da URL da página para saber qual token utilizar nas requisições da API (no `Authentication: Beaer XXXX`).

Abaixo está uma função pronta para isso (utilizada no maker):

```js
function getURLParam(name, defaultValue) {
    var urlParams = new URLSearchParams(window.location.search);
    var value = urlParams.get(name) || defaultValue;
    return value;
};
```

**Comment by GuilhermeGraeff** [comment]
Eu peguei essa issue pois acho que ela vai ser desafiadora e por isso acho que vou aprender bastante realizando ela :)

**Comment by GuilhermeGraeff** [comment]
Primeiramente eu imaginei que consiguiria realizar esta tarefa, porém não tive como dar muita atenção para ela, por conta das tarefas relacionadas ao treinamento da aura. Então, infelizmente, não consegui finalizar. 

Após tentar fazer a integração do chat do framework7 diretamente para o Laraval, decidi que desenvolveria a tela do zero, utilizando o Livewire (que está deu certo a parte do layout e tudo, só tem que ver se tá bonito msm), as requisições para conseguir as respostas da aura pela api consegui instalar os ambientes e funcionam de boa (testadas pelo POSTMAN), porém estou com problemas em realizar as requisições do próprio laravel para a api :(

<hr />
Assim ficou o chat ( pra dar uma ideia de como está ficando :) ): 

![image](https://user-images.githubusercontent.com/48657331/147000559-8e20aa28-236a-4f1d-abd2-d1eb8f4aac1f.png)

**Comment by GuilhermeGraeff** [comment]
Por enquanto ela ainda não está respondendo como deve, mas tá respondendo :)
Desenvolvi o chat sem autenticação para colocar nos serviços do PRACTICE.
Eu enxertei um iframe no site do mural para testar, futuramente pode ser feito um botão e tudo...

![image](https://user-images.githubusercontent.com/48657331/150126713-5936b13c-c4fb-49eb-87a5-8d9e1e9e3c97.png)
