### ISSUE TITLE
Adicionar o tema dark para o widget da Aura

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/api#44]
Os APPs dispõem de um modo escuro e um modo claro, talvez de pra colocar como parâmetro na rota algo como 'mode=dark/light' que adapta o css.

Passar como parâmetro na rota: 

```/v0/widgets/aura?token=kqwmdkqwd123k12p1ked12de12&type=fullscreen&theme=dark```
```/v0/widgets/aura?token=kqwmdkqwd123k12p1ked12de12&type=fullscreen&theme=light```

**Comment by alissonpeloso** [comment]
ótima ideia, assim, no dispositivo se for alterado o tema, simplesmente é trocado a rota do widget
