### ISSUE TITLE
Bug: Chat da aura 'congela' em alguns momentos

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/api#49]
Esse bug, para mim, é bem fora do comum, ele acontece periódicamente vez sim vez não, assim que você der o F5 ele volta a funcionar, e se tu apertar F5 denovo o erro volta a aparecer, e assim por diante.

Este erro passou despercebido por mim e acabou indo para dev, assim que o encontrei, investi um tempo para tentar achar uma solução, não encontrtei, daí por isso que crio esta issue.

![image](https://user-images.githubusercontent.com/48657331/167400035-325ebd1f-8fcf-44de-83d3-e197aa096d78.png)

**Comment by GuilhermeGraeff** [comment]
Ainda não encontrei a solução para este problema, aqui vai algumas considerações, só para mostrar o meu progresso.

Achei pessoas com erros semelhantes em sites como stackoverflow e outros, nenhuma das soluções propostas ajudaram a resolver o caso da Aura.

O erro é complicado, aparentemente está ligado ao Livewire, no arquivo: public/vendor/livewire. Como aparenta ser um erro interno no Livewire, podemos ir testando diferentes entradas e ir removendo coisas do front/back pra tentar encontrar o motivo, ainda estou em processo de ir testando até encontrar o que causa o problema.

Seguimos tentando achar a solução ... :)

**Comment by GuilhermeGraeff** [comment]
Essa issue foi resolvida por osmose na issue #45, eu nem tentei corrigir, o problema simplesmente desapareceu :cow2:, só agradecer.

E tomara que ela não volte a nos assombrar :ghost: no futuro :), senão vamos ter que reabrir essa issue aqui

**Comment by GuilhermeGraeff** [comment]
Essa issue foi resolvida por osmose na issue #45, eu nem tentei corrigir, o problema simplesmente desapareceu :cow2:, só agradecer.

E tomara que ela não volte a nos assombrar :ghost: no futuro :), senão vamos ter que reabrir essa issue aqui

**Comment by alissonpeloso** [comment]
Não consegui encontrar nenhuma forma de corrigir isso, deixaremos a issue de lado por enquanto.

**Comment by alissonpeloso** [comment]
Como a aura será migrada, irei fechar essa issue
