### ISSUE TITLE
Tratar mensagem da Aura com Links

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/api#65]
Quando a aura envia uma mensagem que contem um link, esse link fica apenas como texto. O objetivo dessa tarefa é buscar um pattern pra capturar o link e criar uma tag clicável para que o usuário possa navegar. 

**OBS:** Acredito que seja uma boa ideia adicionar a classe "link external" assim nos aplicativos ele irá abrir no navegador externo (assim espero). ex: `<a class="link external" href="${url}">Acessar</a>`

**Comment by CleissonVieira** [comment]
Vale apena testar também com `target="_blank"`:
<a href="${url}" target="_blank">Acessar</a>
