### ISSUE TITLE
Criar uma tela baseada no widget da aura com melhorias visuais

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/api#66]
O widget da aura será utilizado em todas as nossas aplicações.

A ideia é que a o widget de tela cheia seja usado no mobile: (Aplicativos)
![image](https://user-images.githubusercontent.com/51202705/175525066-6a9bc843-defa-44f1-ab20-30b374ba9276.png)

![image](https://user-images.githubusercontent.com/51202705/175525111-2d0dd53f-5ae4-461c-bd2a-2ce2ac68011c.png)

E que o widget com botão seja usado nos sistesmas web:

![image](https://user-images.githubusercontent.com/51202705/175525476-7f7f7d4d-711c-4bf7-a451-9ab206f9f969.png)

![image](https://user-images.githubusercontent.com/51202705/175525513-5013cd3b-1c9a-4613-912f-f0bd1b05bf49.png)

---

Pode se basear nessas telas que já existem. Pode usar o figma pra fazer as telas

**Comment by SWE3T** [comment]
@alissonpeloso, fiquei com uma dúvida, o objetivo dessa tarefa é criar um protótipo de alta fidelidade para esses widgets no figma?

**Comment by alissonpeloso** [comment]
Isso mesmo

**Comment by alissonpeloso** [comment]
@SWE3T, assim que finalizar, acho que poderia criar uma tarefa para implementar o layout que você criou

**Comment by SWE3T** [comment]
Cheguei nesse resultado: 
https://www.figma.com/file/wFQD7LssXuBkGJXWL6K7uN/Aura-DS?node-id=0%3A1

Caso alguém queira acesso para poder editar o arquivo, é só me marcar e mandar o email que eu adiciono, o figma não tem uma opção padrão para qualquer pessoa com o link poder editar. 

Quanto as cores, eu acredito que elas poderão ter alterações, mas as que estão no momento já estão bem harmonizadas. 


Eu vou criar a tarefa para começar a implementação logo a seguir.
