### ISSUE TITLE
Parsear informação do calendário acadêmico em uma estrutura json de datas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/api#7]
O mais fácil é, a partir de uma URL do calendário, obter os dados em HTML da página e, a partir dela, criar o json.

O [calendário acadêmicio](https://www.uffs.edu.br/atos-normativos/resolucao/consuni/2021-0066) é aquele que é mostrado com vários meses e afins:

![image](https://user-images.githubusercontent.com/512405/121356824-9e234e00-c907-11eb-8dbd-9ca6d302ac3f.png)

O json de saída deve ter os campos `data_inicio`, `data_fim`, `titulo` e `envolvidos`

**Comment by GuilhermeGraeff** [comment]
Neste [link](https://parsecallendar.000webhostapp.com/) está o meu progresso até agora. 

Consegui parsear as infos do calendário da UFFS para um array de **meses** que contém um array de **eventos**, tais eventos tem na posição [0] a data e o evento de acontecimento juntos, em "_start_on_" a data de início deste evento, em "_ends_on_" a data de término deste evento e em "description" está a descrição do evento separada da data.

Vale ressaltar que se o evento não contém data de término (exemplo: 16 – Carnaval – Recesso administrativo.) a data é armazenada em _start_on_, a posição do array associativo _ends_on_ estará vazia ("").

```
["february"]=>
      array(2) {
            [0]=>
                  array(4) {
                        [0]=>string(43) "16 – Carnaval – Recesso administrativo."
                        ["start_on"]=> string(2) "16"
                        ["ends_on"]=> string(0) ""
                        ["description"]=> string(36) "Carnaval – Recesso administrativo."
                  }
            [1]=>
                  array(4) {
                        [0]=>string(62) "17 – Quarta-feira de Cinzas (ponto facultativo ate as 14 h)."
                        ["start_on"]=> string(2) "17"
                        ["ends_on"]=> string(0) ""
                        ["description"]=> string(55) "Quarta-feira de Cinzas (ponto facultativo ate as 14 h)."
                  }
      }
```

**Ainda estou trabalhando ainda para fazer a integração para que o calendário possa ser solicitado através da API.**

**Comment by Dovyski** [comment]
Muito bom, @GuilhermeGraeff . Eu acho que antes de colocarmos essa informação na API, o melhor seriamos criar um pacote/lib que faça essa extração. Dessa forma, podemos utilizar ela em outros projetos/apis. [Esse](https://github.com/ccuffs/auth-iduffs) é um pacote/lib do curso de cc (basta pesquisar por _how to create a php package_), talvez possamos fazer uma para esse código que você está fazendo.

Além disso, eu acho interessante testar o seu código com pelo menos outros dois calendários acadêmicos (talvez de 2020.2 e 2020.1?).

**Comment by alissonpeloso** [comment]
Issue resolvida pelo pacote criado pelo @Dovyski: https://github.com/ccuffs/uffs-ca-scraping
