### ISSUE TITLE
Implementar um popup do calendário acadêmico para o widget da aura

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/api#70]
Na `API` temos a classe: `AcademicCalendarController`
Essa classe utiliza um plugin de scrapper `\CCUFFS\Scrap\AcademicCalendarUFFS` para pegar informações do calendário acadêmico.

O objetivo dessa issue é implementar um tipo de popup que será utilizado no widget da aura mostrando o calendário acadêmico.

**Comment by stefanimeneghetti** [comment]
Eu gerei o calendário para facilitar a visualização das datas mas para adicionar os eventos ao popup eu vou primeiro finalizar a issue #83 já que agora é inviável requisitar os dados sempre que a página é acessada.
