### ISSUE TITLE
Implementar as melhorias visuais da Aura

### ISSUE THREAD

**Issue by SWE3T** [practice-uffs/api#79]
Atualizar o visual do chat da Aura baseando se nesse documento: https://www.figma.com/file/wFQD7LssXuBkGJXWL6K7uN/Aura-DS?node-id=0%3A1

Baseada na Issue #66

**Comment by GuilhermeGraeff** [comment]
Vou só comentar aqui que eu gostaria de ajudar a revisar o pr dessa issue :P

**Comment by SWE3T** [comment]
@practice-uffs/dev, Se vocês puderem testar a implementação do novo visual;

Da forma que eu fiz, ele entra para o modo mobile se a tela for menor que 450px de largura, e caso for maior, vai para o modo de canto; Fica mais fácil entender abrindo o arquivo esse arquivo HTML: 

[teste.zip](https://github.com/practice-uffs/api/files/9260268/teste.zip) Só descompactar e abrir, deve funcionar;

(Tem que estar zipado para o GitHub aceitar :P)

**Comment by SWE3T** [comment]
Lembrando que como eu estou hosteando pelo Ngrok, isso só deve ficar no ar por algumas horas

**Comment by SWE3T** [comment]
Vou marcar essa issue como close, as implementações foram feitas na branch 79, mas como mudaremos de tecnologia acho que um PR seria desnecessário; 

Acho válido utilizar o arquivo teste.zip que está no comentário acima para orientar na próxima implementação do iFrame;
