### ISSUE TITLE
Modificar o formato dos links nas planilhas

### ISSUE THREAD

**Issue by stefanimeneghetti** [practice-uffs/api#81]
Na issue #65 foi adicionado um tratamento para a aura exibir os links de forma clicável porém em algumas respostas da aura o link não aparece na forma de texto então não é possível trata-lo. O objetivo dessa issue é modificar todos os links das planilhas que não aparecem como texto para que a Aura consiga trata-los.

Todas as planilhas podem ser encontradas no link: https://drive.google.com/drive/folders/10Kvb39jEZzC0VyMAOQ3XfV7gTsaWIQHj

**Comment by stefanimeneghetti** [comment]
Alterei o formato dos links em todas as planilhas mas neste processo percebi que o tratamento para links no formato `[texto](url)` implementado na issue #65  não funciona como o esperado então não é possível utiliza-lo no momento.

**Comment by alissonpeloso** [comment]
-[ ] Implementar formato `[texto](url)` para links na planilha da aura
